First draft of report complete

diff --git a/src/summarise b/src/summarise
--- a/src/summarise
+++ b/src/summarise
@@ -1,7 +1,9 @@
 #!/bin/bash
 format='tcpdump'
 input='./'
-output='./out.csv'
+config=''
+outfilename=$(date +'%F_%H-%M-%S')
+output="./${outfilename}_summary.csv"
 start=$(date +%s)
 tmpdir=$(mktemp -d "../tmp.XXXXXX")
 tmpassoc=$(mktemp "${tmpdir}/summarise-associations.XXXXXX.csv")
@@ -18,7 +20,8 @@ print_usage() {
     exit 0
 }
 
-while getopts 'f:hi:o:' flag; do
+
+while getopts 'f:hi:o:c:' flag; do
     case "${flag}" in
         f) format="${OPTARG}"
             ;;
@@ -28,28 +31,76 @@ while getopts 'f:hi:o:' flag; do
             ;;
         o) output="${OPTARG}"
             ;;
+        c) config="${OPTARG}"
+            ;;
         *) print_usage
             exit 1 ;;
     esac
 done
 
+print_progress() {
+    ten=$(expr 10 '*' ${thisfile})
+    div=$(expr ${ten} / ${nofiles})
+    round=$(echo ${div} | awk '{print int($1)}')
+    case "${round}" in
+        1) echo -ne "[#         ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        2) echo -ne "[##        ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        3) echo -ne "[###       ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        4) echo -ne "[####      ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        5) echo -ne "[#####     ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        6) echo -ne "[######    ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        7) echo -ne "[#######   ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        8) echo -ne "[########  ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        9) echo -ne "[######### ] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+        10) echo -ne "[##########] associations extracted from $thisfile/$nofiles files\r"
+            ;;
+    esac
+}
+
 echo "source,destination,start,fin,AP" > "${tmpassoc}"
-echo "Unzipping .gz files from "${input}" and extracting associations..."
+files=$(find ${input} -name '*.gz')
+nofiles=$(find ${input} -name '*.gz' | wc -l)
+thisfile=1
+echo "Number of input files found: ${nofiles}"
+echo "Unzipping .gz files and extracting associations..."
 if [[ "${format}" == "tcpdump" ]]
 then
-    for FILE in $(find ${input} -name '*.gz')
+    if [["${config}" != '']]
+    then
+        echo "WARNING: configuration file ${config} will not be used."
+    fi
+    for FILE in ${files}
     do
+        print_progress
         (gzip -dc "${FILE}" | parse_associations/parse_tcpdump -) 1>> "${tmpassoc}"
+        thisfile=$(expr ${thisfile} + 1)
     done
 elif [[ "${format}" == "syslog" ]]
 then
-    for FILE in $(find "${input}" -name '*.gz')
+    if [[ "${config}" == '' ]]
+    then
+        echo "ERROR: configuration file must be specified for ${format} format." 1>&2
+        rm -r "${tmpdir}"
+        exit 1
+    fi
+    for FILE in ${files}
     do
-        (gzip -dc "${FILE}" | python3 parse_associations/parse_syslog.py -) 1>> "${tmpassoc}"
+        print_progress
+        (gzip -dc "${FILE}" | python3 parse_associations/parse_syslog.py "${config}") 1>> "${tmpassoc}"
+        thisfile=$(expr ${thisfile} + 1)
     done
 fi
-echo "Finding access points and encounters..."
-matlab -nojvm -nodisplay -nosplash -batch "find_encounters('${tmpassoc}','${tmpaps}','${output}'); quit" 1>/dev/null
+echo "Finding access points and encounters...                           "
+matlab -nojvm -nodisplay -nosplash -batch "find_encounters('${tmpassoc}','${tmpaps}','${output}'); quit"
 ap=$(cat ${tmpaps} | wc -l)
 end=$(date +%s)
 runtime=$(expr ${end} - ${start})
